@startuml
cloud {
    package "GitHub" as github{
        database "msa-recap repository"  {
            [Source Code] as SC
            [GitHub Actions] as GA
        }
    }
}

cloud {
    [Internet] as internet
}

package "Azure" {
    
    database "Azure Cloud Storage" as cs {
        [Video Storage bucket]
    }

    node "Azure Static Web App" as FA {
        frame "Web App" as WA {
            [Azure Upload] as AU
            [Audio Capture] as AC
            [Video Capture] as VC
            [Video Upload] as VU
            [Video Download] as VD
            [Video Playback] as VP
            [Feedback Form] as FF
            [HTML Web Pages] as HTML

        }

        frame "API" {
            [Azure API]
            [HTTPJSONTranscript]
            [ProjectName]
        }

    }

    [Azure Service Plan]

}

actor User as user

SC --> GA : run workflow
GA --> FA : push to Azure
FA --> user : show web page
FA <--> cs : store & retrieve video
API -r-> internet : show web page
API <--> WA : API calls

@enduml
